project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: metaflow

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: General utilities
      desc: General purpose utilities.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - step
        - current
        - S3
    - title: Documentation utilities
      desc: Utilities for documentation.
      contents:
        - FlowSpec
    - title: Decorators
      desc: decorators for metaflow
      contents:
        - conda_base
      dynamic: true

  