project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: modal

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: General utilities
      desc: General purpose utilities.
      dynamic: true
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - client
        - config
        - gpu
    - title: Documentation utilities
      desc: Utilities for documentation.
      dynamic: true
      contents:
        - mount
        - image
        - app


  