project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: metaflow

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Decorators
      desc: decorators for metaflow
      contents:
        - name: conda_base
          members: ["conda_base"]
          dynamic: true

  