project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package
  package: modal

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Documentation utilities
      desc: Utilities for documentation.
      dynamic: true
      contents:
        - functions
        - functions.web_endpoint

  