# config { #modal.config }

`config`

## .Modal.Toml


The ``.modal.toml`` file is generally stored in your home directory.
It should look like this::

```toml
[default]
token_id = "ak-12345..."
token_secret = "as-12345..."
```

You can create this file manually, or you can run the ``modal token set ...``
command (see below).



## Setting Tokens Using The Cli


You can set a token by running the command::

```bash
modal token set   --token-id <token id>   --token-secret <token secret>
```

This will write the token id and secret to ``.modal.toml``.

If the token id or secret is provided as the string ``-`` (a single dash),
then it will be read in a secret way from stdin instead.



## Other Configuration Options


Other possible configuration options are:

* ``loglevel`` (in the .toml file) / ``MODAL_LOGLEVEL`` (as an env var).
  Defaults to ``WARNING``.
  Set this to ``DEBUG`` to see a bunch of internal output.
* ``logs_timeout`` (in the .toml file) / ``MODAL_LOGS_TIMEOUT`` (as an env var).
  Defaults to 10.
  Number of seconds to wait for logs to drain when closing the session,
  before giving up.
* ``automount`` (in the .toml file) / ``MODAL_AUTOMOUNT`` (as an env var).
  Defaults to True.
  By default, Modal automatically mounts modules imported in the current scope, that
  are deemed to be "local". This can be turned off by setting this to False.
* ``server_url`` (in the .toml file) / ``MODAL_SERVER_URL`` (as an env var).
  Defaults to ``https://api.modal.com``.
  Not typically meant to be used.



## Meta-Configuration


Some "meta-options" are set using environment variables only:

* ``MODAL_CONFIG_PATH`` lets you override the location of the .toml file,
  by default ``~/.modal.toml``.
* ``MODAL_PROFILE`` lets you use multiple sections in the .toml file
  and switch between them. It defaults to "default".

## Attributes

| Name | Description |
| --- | --- |
| [ch](#modal.config.ch) |  |
| [config](#modal.config.config) |  |
| [log_level_numeric](#modal.config.log_level_numeric) |  |
| [logger](#modal.config.logger) |  |
| [user_config_path](#modal.config.user_config_path) |  |

## Functions

| Name | Description |
| --- | --- |
| [config_profiles](#modal.config.config_profiles) | List the available modal profiles in the .modal.toml file. |
| [config_set_active_profile](#modal.config.config_set_active_profile) | Set the user's active modal profile by writing it to the `.modal.toml` file. |

### config_profiles { #modal.config.config_profiles }

`config.config_profiles()`

List the available modal profiles in the .modal.toml file.

### config_set_active_profile { #modal.config.config_set_active_profile }

`config.config_set_active_profile(env)`

Set the user's active modal profile by writing it to the `.modal.toml` file.